name: ci

on:
    pull_request:

jobs:
    linux_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
                phpunit-versions: ['4.8.36']
                include:
                  - php: '8.0'
                    phpunit-versions: '9.5.1'
                  - php: '8.1'
                    phpunit-versions: '9.6.13'
                  - php: '8.2'
                    phpunit-versions: '9.6.13'
                  - php: '8.3'
                    phpunit-versions: '9.6.13'

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2, phpunit:${{ matrix.phpunit-versions }}

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: phpunit --stop-on-fail
